USE [master]
GO
CREATE DATABASE [dswMLM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dswMLM', FILENAME = N'C:\MSSQL\MSSQL12.MSSQLSERVER\MSSQL\DATA\dswMLM.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 30720KB )
 LOG ON 
( NAME = N'dswMLM_log', FILENAME = N'C:\MSSQL\MSSQL12.MSSQLSERVER\MSSQL\DATA\dswMLM_log.ldf' , SIZE = 25600KB , MAXSIZE = 2048GB , FILEGROWTH = 20480KB )
GO
ALTER DATABASE [dswMLM] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dswMLM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dswMLM] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dswMLM] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dswMLM] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dswMLM] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dswMLM] SET ARITHABORT OFF 
GO
ALTER DATABASE [dswMLM] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dswMLM] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dswMLM] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dswMLM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dswMLM] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dswMLM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dswMLM] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dswMLM] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dswMLM] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dswMLM] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dswMLM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dswMLM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dswMLM] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dswMLM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dswMLM] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dswMLM] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dswMLM] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dswMLM] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [dswMLM] SET  MULTI_USER 
GO
ALTER DATABASE [dswMLM] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dswMLM] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dswMLM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dswMLM] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [dswMLM] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dswMLM] SET  READ_WRITE 
GO
